import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import Testimonial from "./components/testimonial";
import Title from "./components/title";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <canvas id="c"></canvas>
        <Title sub_title='Welcome' title='Home' description= 'Building An Electric Vehicle Charging Network, Shared By Billions.'/>
    </div>
  )
}
