import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import Testimonial from "./components/testimonial";
import Title from "./components/title";
import Hero from "./components/hero";


export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>


            <div className='relative'>
                <Hero sub_title='Welcome' title='Tuk Token' description='Power the Transport rEVolution and Earn'/>

                <div className="bg-[#2b3233] relative">
                    <div className="mx-auto max-w-7xl pt-12 pb-6 px-4 sm:px-6 lg:px-8">
                        <div className="text-center">
                            <h2 className="mt-1 text-4xl font-bold tracking-tight text-white sm:text-3xl">Earn TUK by
                                Expanding the eTukTuk Network</h2>
                        </div>


                        <h3 className="mt-6 text-4xl font-bold tracking-tight text-white sm:text-2xl">How We do It</h3>
                        <ul className="mt-4 text-white">
                            <li className="mt-2">- Drivers will pay to recharge their vehicles, creating network
                                revenue.
                            </li>
                            <li className="mt-2">- Territory Partners and Power Stakers earn TUK every time a
                                transaction is processed.
                            </li>
                            <li className="mt-2">- We scale the network up, cutting the ties that bind us to expensive
                                fossil fuels.
                            </li>
                            <li className="mt-2">- We will expand the solution throughout other regions, growing the
                                earning potential of drivers and the community.
                            </li>
                        </ul>

                        <h3 className="mt-6 text-4xl font-bold tracking-tight text-white sm:text-2xl">Earn It</h3>
                        <ul className="mt-4 text-white">
                            <li className="mt-2 font-bold">Territory Partner.</li>
                            <li className="mt-2">- Become an eTukTuk Territory Partner and run the nodes that will power
                                the sustainable charging network that developing countries sorely need.
                            </li>
                            <li className="mt-2 font-bold">Power Staking</li>
                            <li className="mt-2">- As more people join the community, the network will grow.</li>
                        </ul>

                        <h3 className="mt-6 text-4xl font-bold tracking-tight text-white sm:text-2xl">The Vault</h3>
                        <ul className="mt-4 text-white">
                            <li className="mt-2">Lock it in. Create your Vault and join the rEvolutionary ecosystem that’s designed to change the transportation sector as we know it.</li>
                        </ul>
                        <button type="submit"
                                className="w-48 block mt-6 w-full rounded-md border border-transparent bg-[#00aeef] px-5 py-3 text-base font-medium text-white shadow hover:bg-[#32393a]-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600 sm:px-10">
                            Go To Vault
                        </button>
                    </div>
                </div>

                <div className="bg-[#2b3233] relative" style={{
                    'z-index': '-1'
                }}>
                    <div className="box-container">
                        <div className="box">
                            <div className="glass"></div>
                            <div className="content">
                                <h1>Glowing Border</h1>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim quis sint deleniti quas facere
                                    non error adipisci quo labore nam. Nobis sapiente, facilis explicabo possimus iure suscipit
                                    hic sunt praesentium.</p>
                            </div>
                        </div>
                        <div className="box">
                            <div className="glass"></div>
                            <div className="content">
                                <h1>Glowing Border</h1>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim quis sint deleniti quas facere
                                    non error adipisci quo labore nam. Nobis sapiente, facilis explicabo possimus iure suscipit
                                    hic sunt praesentium.</p>
                            </div>
                        </div>
                        <div className="box">
                            <div className="glass"></div>
                            <div className="content">
                                <h1>Glowing Border</h1>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim quis sint deleniti quas facere
                                    non error adipisci quo labore nam. Nobis sapiente, facilis explicabo possimus iure suscipit
                                    hic sunt praesentium.</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="bg-[#2b3233] relative">
                    <div className="mx-auto max-w-7xl pt-12 pb-6 px-4 sm:px-6 lg:px-8">
                        <div className="text-center">
                            <h2 className="mt-1 text-4xl font-bold tracking-tight text-white sm:text-3xl">Why
                                Blockchain</h2>
                        </div>
                    </div>
                </div>

                <div className="bg-[#2b3233] relative">
                    <div className="mx-auto max-w-7xl pt-12 pb-6 px-4 sm:px-6 lg:px-8">
                        <div className="text-center">
                            <h2 className="mt-1 text-4xl font-bold tracking-tight text-white sm:text-3xl">Why
                                Cardano</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
